// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdPo4PrRGWVmMXk-nMNq7NopeT7gpzscI',
    appId: '1:847991656194:web:cd57823e21d52c5aea7c1b',
    messagingSenderId: '847991656194',
    projectId: 'wouldulikedbaa',
    authDomain: 'wouldulikedbaa.firebaseapp.com',
    databaseURL: 'https://wouldulikedbaa-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'wouldulikedbaa.appspot.com',
    measurementId: 'G-LEYN5K85Q9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIhL2crUTiQmH6Zc8AUZBV5Q3ijFybEZ0',
    appId: '1:847991656194:android:240d78b2a61cabf9ea7c1b',
    messagingSenderId: '847991656194',
    projectId: 'wouldulikedbaa',
    databaseURL: 'https://wouldulikedbaa-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'wouldulikedbaa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXhffTGEKKpfGtI2uvFLJoXxTPXbw22Wo',
    appId: '1:847991656194:ios:17782db06ce4de87ea7c1b',
    messagingSenderId: '847991656194',
    projectId: 'wouldulikedbaa',
    databaseURL: 'https://wouldulikedbaa-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'wouldulikedbaa.appspot.com',
    iosBundleId: 'com.example.wouldulikeaii',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXhffTGEKKpfGtI2uvFLJoXxTPXbw22Wo',
    appId: '1:847991656194:ios:17782db06ce4de87ea7c1b',
    messagingSenderId: '847991656194',
    projectId: 'wouldulikedbaa',
    databaseURL: 'https://wouldulikedbaa-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'wouldulikedbaa.appspot.com',
    iosBundleId: 'com.example.wouldulikeaii',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdPo4PrRGWVmMXk-nMNq7NopeT7gpzscI',
    appId: '1:847991656194:web:db35539841eb9443ea7c1b',
    messagingSenderId: '847991656194',
    projectId: 'wouldulikedbaa',
    authDomain: 'wouldulikedbaa.firebaseapp.com',
    databaseURL: 'https://wouldulikedbaa-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'wouldulikedbaa.appspot.com',
    measurementId: 'G-82DRSR76TF',
  );
}
